/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-08-09 09:14:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import worldhourproject.controller.WHPView;
import worldhourproject.controller.WHPView;

public final class add_002dcountry_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/jsp/../javascript/dropdown-list-selection.js", Long.valueOf(1691565705642L));
    _jspx_dependants.put("/jsp/../css/navbar.css", Long.valueOf(1691150694498L));
    _jspx_dependants.put("/jsp/../css/admin.css", Long.valueOf(1691566915521L));
    _jspx_dependants.put("/jsp/navbar.jsp", Long.valueOf(1691162353425L));
    _jspx_dependants.put("/jsp/../css/add-page-admin.css", Long.valueOf(1691154382648L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("worldhourproject.controller.WHPView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" charset=\"UTF-8\">\r\n");
      out.write("	<title>World Hour Project Add Country</title>\r\n");
      out.write("	<style> ");
      out.write(".header-container {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-title {\r\n");
      out.write("	padding-top: 1%;\r\n");
      out.write("	padding-bottom: 1%;\r\n");
      out.write("	margin-left: 2%;\r\n");
      out.write("	margin-right: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home-page-title {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home-page-title:hover {\r\n");
      out.write("	color: cadetblue;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}");
      out.write(" </style>\r\n");
      out.write("	<style> ");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-container {\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-container-title {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-button {\r\n");
      out.write("	padding: 0.8%;\r\n");
      out.write("	margin-bottom: 3%;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	border: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width:auto;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	table-layout: fixed;\r\n");
      out.write("	width: 75%;\r\n");
      out.write("	/*width: auto;*/\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl-col-names {\r\n");
      out.write("	border: 2px solid blueviolet;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl td, .tbl-col-names th {\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("  	border: 1px solid #dddddd;\r\n");
      out.write("  	text-align: center;\r\n");
      out.write("  	/*width: auto;\r\n");
      out.write("  	white-space:nowrap;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl tr:nth-child(even) {\r\n");
      out.write("  background-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-del-btns {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-button, .delete-button {\r\n");
      out.write("	border: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width:auto;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	margin-left: 3%;\r\n");
      out.write("	margin-right: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-button {\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-button {\r\n");
      out.write("	background-color: darkred;\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write("	<style> ");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-form-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-form {\r\n");
      out.write("	width: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".insert-text, .option-selection {\r\n");
      out.write("	margin-bottom: 3%;\r\n");
      out.write("	padding: 1%;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	border: 2% solid palevioletred;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("}");
      out.write(" </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-container\">\r\n");
      out.write("	<div class=\"header-title\">\r\n");
      out.write("		<span class=\"home-page-title\" onclick=\"window.location.href='");
      out.print(WHPView.AdminPage);
      out.write("'\">WHP Admin</span>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"content-container\">\r\n");
      out.write("		<p class=\"content-container-title\">Add a New Country</p>\r\n");
      out.write("		<div class=\"add-form-container\">\r\n");
      out.write("			<form class=\"add-form\" action=\"");
      out.print(WHPView.AddCountryServlet );
      out.write("\" method=\"post\">\r\n");
      out.write("				<label for=\"cname\">Country Name</label>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Type a Country Name\" class=\"insert-text\" id=\"cname\" name=\"cname\">\r\n");
      out.write("				<label for=\"ccapital\">Country Capital</label>\r\n");
      out.write("				<input type=\"text\" placeholder=\"Type Country's Capital\" class=\"insert-text\" id=\"ccapital\" name=\"ccapital\">\r\n");
      out.write("				<label for=\"ccontinent\">Country Continent</label>\r\n");
      out.write("				<select class=\"option-selection\" id=\"ccontinent\" name=\"ccontinent\">\r\n");
      out.write("					<option value=\"Africa\" selected>Africa</option>\r\n");
      out.write("					<option value=\"America\">America</option>\r\n");
      out.write("					<option value=\"Asia\">Asia</option>\r\n");
      out.write("					<option value=\"Atlantic\">Atlantic</option>\r\n");
      out.write("					<option value=\"Australia\">Australia</option>\r\n");
      out.write("					<option value=\"Europe\">Europe</option>\r\n");
      out.write("					<option value=\"Indian\">Indian</option>\r\n");
      out.write("					<option value=\"Pacific\">Pacific</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<div class=\"btn-container\">\r\n");
      out.write("					<button type=\"submit\" class=\"add-button\" id=\"add-button\">Add Country</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"successful-db-insertion\">\r\n");
      out.write("			<script type=\"text/javascript\" src=\"//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js\"></script>\r\n");
      out.write("			<script type=\"text/javascript\">");
      out.write("$(document).ready(function() {\r\n");
      out.write("	$('#add-button').click(function(e) {\r\n");
      out.write("		var countryName = $('#cname').val();\r\n");
      out.write("		var capitalName = $('#ccapital').val();\r\n");
      out.write("		var continentName = $('#ccontinent option:selected').val();\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: 'post',\r\n");
      out.write("			url: \"");
      out.print(WHPView.AddCountryServlet );
      out.write("\",\r\n");
      out.write("			data: { \r\n");
      out.write("				cname: countryName,\r\n");
      out.write("				ccapital: capitalName,\r\n");
      out.write("				ccontinent: continentName\r\n");
      out.write("				},\r\n");
      out.write("			success: function(msg) {\r\n");
      out.write("				$('#successful-db-insertion').text(msg);\r\n");
      out.write("				window.location = \"");
      out.print(WHPView.AdminPage );
      out.write("\";\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		\r\n");
      out.write("	})\r\n");
      out.write("});");
      out.write("</script>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
