/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-08-09 10:36:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.Connection;
import java.util.List;
import com.worldhourproject.utility.JDBCDataSource;
import worldhourproject.controller.WHPView;
import com.worldhourproject.dao.CountryDAO;
import com.worldhourproject.bean.CountryBean;
import worldhourproject.controller.WHPView;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/jsp/../css/navbar.css", Long.valueOf(1691150694498L));
    _jspx_dependants.put("/jsp/../css/admin.css", Long.valueOf(1691566915521L));
    _jspx_dependants.put("/jsp/navbar.jsp", Long.valueOf(1691162353425L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.worldhourproject.dao.CountryDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("com.worldhourproject.utility.JDBCDataSource");
    _jspx_imports_classes.add("worldhourproject.controller.WHPView");
    _jspx_imports_classes.add("com.worldhourproject.bean.CountryBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" charset=\"UTF-8\">\r\n");
      out.write("		<title>World Hour Project Admin Page</title>\r\n");
      out.write("		<style> ");
      out.write(".header-container {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".header-title {\r\n");
      out.write("	padding-top: 1%;\r\n");
      out.write("	padding-bottom: 1%;\r\n");
      out.write("	margin-left: 2%;\r\n");
      out.write("	margin-right: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home-page-title {\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".home-page-title:hover {\r\n");
      out.write("	color: cadetblue;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}");
      out.write(" </style>\r\n");
      out.write("		<style> ");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-container {\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content-container-title {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-bottom: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-container {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add-button {\r\n");
      out.write("	padding: 0.8%;\r\n");
      out.write("	margin-bottom: 3%;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	border: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width:auto;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("	table-layout: fixed;\r\n");
      out.write("	width: 75%;\r\n");
      out.write("	/*width: auto;*/\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl-col-names {\r\n");
      out.write("	border: 2px solid blueviolet;\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("	height: 35px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl td, .tbl-col-names th {\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("  	border: 1px solid #dddddd;\r\n");
      out.write("  	text-align: center;\r\n");
      out.write("  	/*width: auto;\r\n");
      out.write("  	white-space:nowrap;*/\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tbl tr:nth-child(even) {\r\n");
      out.write("  background-color: #dddddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-del-btns {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-button, .delete-button {\r\n");
      out.write("	border: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	width:auto;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	margin-left: 3%;\r\n");
      out.write("	margin-right: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".edit-button {\r\n");
      out.write("	background-color: blueviolet;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".delete-button {\r\n");
      out.write("	background-color: darkred;\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"header-container\">\r\n");
      out.write("	<div class=\"header-title\">\r\n");
      out.write("		<span class=\"home-page-title\" onclick=\"window.location.href='");
      out.print(WHPView.AdminPage);
      out.write("'\">WHP Admin</span>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"content-container\">\r\n");
      out.write("			<p class=\"content-container-title\">All Countries Details</p>\r\n");
      out.write("			<div class=\"btn-container\">\r\n");
      out.write("				<button class=\"add-button\" onclick=\"window.location.href='");
      out.print(WHPView.AddCountryPage);
      out.write("'\">Add Country</button>\r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("			<table class=\"tbl\">\r\n");
      out.write("				<tr class=\"tbl-col-names\">\r\n");
      out.write("					<th>No.</th>\r\n");
      out.write("					<th>Country Name</th>\r\n");
      out.write("					<th>Country Capital</th>\r\n");
      out.write("					<th>Country Continent</th>\r\n");
      out.write("					<th>Country Date and Time</th>\r\n");
      out.write("					<th>Action</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				");

					CountryDAO cdao = new CountryDAO(JDBCDataSource.getCon());
					List<CountryBean> countriesList = cdao.getAllCountries();
					for(CountryBean cb : countriesList) {
				
      out.write("\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td>");
      out.print(cb.getId() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(cb.getCountry_name() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(cb.getCountry_capital() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(cb.getCountry_continent() );
      out.write("</td>\r\n");
      out.write("					<td>");
      out.print(cb.getCountryDateTime() );
      out.write("</td>\r\n");
      out.write("					<td>\r\n");
      out.write("						<div class=\"edit-del-btns\">\r\n");
      out.write("							<button class=\"edit-button\" onclick=\"window.location.href='");
      out.print(WHPView.EditCountryPage);
      out.write("?id=");
      out.print(cb.getId() );
      out.write("'\">Edit</button>\r\n");
      out.write("							<button class=\"delete-button\" onclick=\"window.location.href='");
      out.print(WHPView.DeleteCountryServlet);
      out.write("?id=");
      out.print(cb.getId() );
      out.write("'\">Delete</button>\r\n");
      out.write("						</div>\r\n");
      out.write("					</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				\r\n");
      out.write("				");

					}
				
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
