/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.85
 * Generated at: 2023-08-11 08:41:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import worldhourproject.controller.WHPView;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/../javascript/display-country-info.js", Long.valueOf(1691743123802L));
    _jspx_dependants.put("/jsp/../css/index.css", Long.valueOf(1691743312060L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("worldhourproject.controller.WHPView");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>World Hour</title>\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" charset=\"UTF-8\">\r\n");
      out.write("		<style> ");
      out.write("@charset \"UTF-8\";\r\n");
      out.write("\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".main-container {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bckgrnd {\r\n");
      out.write("	opacity: 0.6;\r\n");
      out.write("	background-repeat: no-repeat;\r\n");
      out.write("	background-position: center;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	position: fixed; /*sau absolute numai ca e cu scroll si cuprinde toata imaginea */\r\n");
      out.write("	z-index: -1!important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	white-space: nowrap;\r\n");
      out.write("	padding-top: 10%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search-form {\r\n");
      out.write("	width: 20%;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.insert-text{\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	padding: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-button{\r\n");
      out.write("	border: 2px solid black;\r\n");
      out.write("	width: auto;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	padding: 2%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".result {\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 1.5em;\r\n");
      out.write("\r\n");
      out.write("}");
      out.write(" </style>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"//ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">");
      out.write("$(document).ready(function() {\r\n");
      out.write("	$('#search-button').click(function(e) {\r\n");
      out.write("		var cid = $('#cid').val();\r\n");
      out.write("		var cname = $('#cname').val();\r\n");
      out.write("		var ccapital = $('#ccapital').val();\r\n");
      out.write("		var ccontinent = $('#ccontinent').val();\r\n");
      out.write("		\r\n");
      out.write("		$.ajax ({\r\n");
      out.write("			type: 'post',\r\n");
      out.write("			url: \"");
      out.print(WHPView.MainServlet );
      out.write("\",\r\n");
      out.write("			data: {\r\n");
      out.write("				cid: cid,\r\n");
      out.write("				cname: cname,\r\n");
      out.write("				ccapital: ccapital,\r\n");
      out.write("				ccontinent: ccontinent\r\n");
      out.write("			},\r\n");
      out.write("			success: function(msg) {\r\n");
      out.write("				$('#result').html(msg);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("	});\r\n");
      out.write("});");
      out.write("</script>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body>\r\n");
      out.write("		<div class=\"main-container\">\r\n");
      out.write("			<img  class=\"bckgrnd\" src=\"http://localhost/WorldHourProject/images/back_image.jpg\" alt=\"\">\r\n");
      out.write("			<div class=\"content\">\r\n");
      out.write("				<form action=\"\" class=\"search-form\" id=\"search-form\" method=\"post\">\r\n");
      out.write("					<input type=\"hidden\" id=\"cid\" name=\"cid\">\r\n");
      out.write("					<input type=\"text\" placeholder=\"Type a Country Name\" class=\"insert-text\" id=\"cname\" name=\"cname\">\r\n");
      out.write("					<input type=\"hidden\" id=\"ccapital\" name=\"ccapital\">\r\n");
      out.write("					<input type=\"hidden\" id=\"ccontinent\" name=\"ccontinent\">\r\n");
      out.write("					<button class=\"form-button\" id=\"search-button\">Search</button>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"result\" id=\"result\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
